"""LLM-as-judge scoring using Claude.

Wraps the Anthropic API to implement the Scorer protocol.
Logic migrated from src/pipeline/scoring.py.

Methodology: Saad-Falcon et al. (2024, NAACL) showed LLM-as-judge
correlates well with human judgment for RAG evaluation.

Known limitation: if Claude is also used for query classification,
both features and labels carry Claude's biases. Flagged for future work.
"""

from __future__ import annotations

import anthropic


JUDGE_PROMPT = """You are evaluating the quality of an answer generated by a language model.

**Question:** {query}

**Reference context (ground truth source):**
{context}

**Model's answer:**
{answer}

Rate the answer on three dimensions, each from 1 (worst) to 5 (best):

1. **Faithfulness**: Is the answer factually consistent with the context? (1 = contradicts context, 5 = perfectly faithful)
2. **Relevance**: Does the answer address the question asked? (1 = completely off-topic, 5 = directly answers the question)
3. **Conciseness**: Is the answer appropriately concise without losing important information? (1 = extremely verbose or missing key info, 5 = perfectly concise)

Respond in exactly this format:
faithfulness: <score>
relevance: <score>
conciseness: <score>"""


class ClaudeScorer:
    """LLM-as-judge scoring using Claude.

    Methodology: Saad-Falcon et al. (2024, NAACL) showed LLM-as-judge
    correlates well with human judgment.

    Known limitation: if Claude is also used for query classification,
    both features and labels carry Claude's biases.
    """

    def __init__(self, model: str = "claude-sonnet-4-20250514") -> None:
        """Initialize with the Claude model to use for judging.

        Args:
            model: Anthropic model ID for scoring.
        """
        self._model = model
        self._client = anthropic.Anthropic()

    @property
    def name(self) -> str:
        """Return unique identifier for this scorer."""
        return f"claude:{self._model}"

    def score(self, query: str, context: str, answer: str) -> dict[str, float]:
        """Score a generated answer using Claude as judge.

        Args:
            query: The original question.
            context: The source document text (ground truth).
            answer: The model's generated answer.

        Returns:
            Dict with 'faithfulness', 'relevance', 'conciseness' scores (1-5).
        """
        response = self._client.messages.create(
            model=self._model,
            max_tokens=100,
            messages=[{
                "role": "user",
                "content": JUDGE_PROMPT.format(
                    query=query, context=context, answer=answer
                ),
            }],
        )
        text = response.content[0].text
        scores: dict[str, float] = {}
        for line in text.strip().split("\n"):
            line = line.strip()
            for dimension in ("faithfulness", "relevance", "conciseness"):
                if line.lower().startswith(dimension):
                    try:
                        scores[dimension] = float(line.split(":")[-1].strip())
                    except ValueError:
                        scores[dimension] = 0.0
        return scores
